#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (C) 2024-2026, Advanced Micro Devices, Inc. All rights reserved.
#
# Codegen for the mxfp4_moe gemm1 / gemm2 template instances.
#
# Follows the aiter codegen convention (cf. ck_gemm_moe_2stages_codegen): a
# single codegen class enumerates instance records, fans each out into its own
# .cu translation unit, and emits a string -> function-pointer lookup header.
#
#   * No SplitK variants.
#   * All BM in {16, 32, 64, 128} route through a single template:
#       gemm1: aiter::mxfp4_moe::gemm1::launch
#       gemm2: aiter::mxfp4_moe::gemm2::launch_atomic / launch_nonatomic

import argparse
from pathlib import Path

# ── Supported shape tuples ─────────────────────────────────────────────────
# (NE, D_HIDDEN, D_INTER, TOPK)
SHAPES = [
    (385,  7168,      512,      9),  # Kimi-K2.5 TP=4
    (257,  7168,      512,      9),  # DSR
]

# XCD-swizzle group sizes to enumerate for BM=128 paths (large-M targets).
# 0 = no remap (baseline). 1 = step-1-only (= legacy remap_xcd). Positive N =
# flydsl-style 2-step remap with M-major group size N.
BM128_XCD_SWIZZLES = [0, 1, 2, 4, 8]

# XCD-swizzle group sizes for the smaller-M tiers. These paths default to naive
# split (xcd=0); enumerate small positive groups so the dispatcher can pick the
# XCD-contiguous remap that helps mid-/large-M decode. 0 keeps the bare name.
BM32_XCD_SWIZZLES = [0, 1, 2]
BM16_XCD_SWIZZLES = [0, 1, 2]

# ── Instance file template ─────────────────────────────────────────────────
INSTANCE_HEADER = """// SPDX-License-Identifier: MIT
// Copyright (C) 2024-2026, Advanced Micro Devices, Inc. All rights reserved.
//
// AUTO-GENERATED by gen_instances.py. Do not edit.

#include <hip/hip_runtime.h>
#include <cstdint>

{kernel_include}

extern "C" void {fn_name}(
    hipStream_t stream,
{params})
{{
{body}
}}
"""

G1_CSHUFFLE_PARAMS = """    const void*    A_q,
    const void*    A_scale,
    const void*    B_q,
    const void*    B_scale,
    const int32_t* sorted_expert_ids,
    const int32_t* cumsum,
    const int32_t* m_indices,
    int            n_tokens,
    void*          A_q_out,
    void*          A_scale_out,
    const void*    hidden_ptr"""

G2_ATOMIC_PARAMS = """    const void*    A_q,
    const void*    A_scale,
    const void*    B_q,
    const void*    B_scale,
    const int32_t* sorted_expert_ids,
    const int32_t* cumsum,
    const int32_t* sorted_token_ids,
    const float*   sorted_weights,
    int            M,
    void*          bf16_out"""

G2_NONATOMIC_PARAMS = """    const void*    A_q,
    const void*    A_scale,
    const void*    B_q,
    const void*    B_scale,
    const int32_t* sorted_expert_ids,
    const int32_t* cumsum,
    int            max_sorted,
    void*          bf16_out"""

G1_INC = '#include "gemm_a4w4/gemm1_a4w4.cuh"'
G2_INC = '#include "gemm_a4w4/gemm2_a4w4.cuh"'

# ── Lookup header templates ────────────────────────────────────────────────
LOOKUP_HEADER_HEAD = """// SPDX-License-Identifier: MIT
// Copyright (C) 2024-2026, Advanced Micro Devices, Inc. All rights reserved.
//
// AUTO-GENERATED by gen_instances.py.

#pragma once

#include "mxfp4_moe_gemm_dispatch.h"

// Forward declarations of every codegen'd instance.
"""


# ── Instance record ────────────────────────────────────────────────────────
class Instance:
    """One codegen'd template instance.

    name      kernelName (the CSV dispatch key + the extern "C" symbol).
    fn_type   dispatch::Gemm1CshuffleFn / Gemm2AtomicFn / Gemm2NonatomicFn.
    include   the .cuh that defines the launch<...> template.
    params    extern "C" parameter list (one of the *_PARAMS strings).
    body      the launch<...> call wrapped by the extern "C" function.
    """

    __slots__ = ("name", "fn_type", "include", "params", "body")

    def __init__(self, name, fn_type, include, params, body):
        self.name = name
        self.fn_type = fn_type
        self.include = include
        self.params = params
        self.body = body


def _g1_body(ne, h, e, bm, *, use_nt=False, inline_quant=False, xcd_swizzle=0):
    """Body of an extern "C" wrapper that calls aiter::mxfp4_moe::gemm1::launch."""
    n_out = 2 * e
    if inline_quant:
        return (
            f"    aiter::mxfp4_moe::gemm1::launch<\n"
            f"        {ne}, {h}, {n_out}, /*BM*/{bm},\n"
            f"        /*kUseNT*/{str(use_nt).lower()},\n"
            f"        /*kInlineQuant*/true,\n"
            f"        /*kXcdSwizzle*/{xcd_swizzle}>(\n"
            f"            stream, A_q, A_scale, B_q, B_scale,\n"
            f"            sorted_expert_ids, cumsum, m_indices, n_tokens,\n"
            f"            A_q_out, A_scale_out, hidden_ptr);"
        )
    else:
        return (
            f"    (void)hidden_ptr;\n"
            f"    aiter::mxfp4_moe::gemm1::launch<\n"
            f"        {ne}, {h}, {n_out}, /*BM*/{bm},\n"
            f"        /*kUseNT*/{str(use_nt).lower()},\n"
            f"        /*kInlineQuant*/false,\n"
            f"        /*kXcdSwizzle*/{xcd_swizzle}>(\n"
            f"            stream, A_q, A_scale, B_q, B_scale,\n"
            f"            sorted_expert_ids, cumsum, m_indices, n_tokens,\n"
            f"            A_q_out, A_scale_out);"
        )


def _g2_atomic_body(ne, h, e, topk, bm, *, use_nt=False, xcd_swizzle=0):
    return (
        f"    aiter::mxfp4_moe::gemm2::launch_atomic<\n"
        f"        {ne}, {e}, {h}, {topk}, /*BM*/{bm},\n"
        f"        /*kUseNT*/{str(use_nt).lower()},\n"
        f"        /*kXcdSwizzle*/{xcd_swizzle}>(\n"
        f"            stream, A_q, A_scale, B_q, B_scale,\n"
        f"            sorted_expert_ids, cumsum, sorted_token_ids, sorted_weights,\n"
        f"            M, bf16_out);"
    )


def _g2_nonatomic_body(ne, h, e, *, xcd_swizzle=0):
    return (
        f"    aiter::mxfp4_moe::gemm2::launch_nonatomic<\n"
        f"        {ne}, {e}, {h}, /*kXcdSwizzle*/{xcd_swizzle}>(\n"
        f"            stream, A_q, A_scale, B_q, B_scale,\n"
        f"            sorted_expert_ids, cumsum, max_sorted, bf16_out);"
    )


# ── Codegen ────────────────────────────────────────────────────────────────
class mxfp4_moe_gemm_codegen:
    def __init__(self, working_path):
        self.working_path = Path(working_path)

    # -- instance enumerators ------------------------------------------------
    def enumerate_g1_instances(self):
        for ne, h, e, _topk in SHAPES:
            prefix = f"mxfp4_moe_g1_a4w4_NE{ne}_H{h}_E{e}"

            for use_nt, suffix in [(True, "NT"), (False, "CACHED")]:
                for xcd in BM32_XCD_SWIZZLES:
                    xsuf = "" if xcd == 0 else f"_XCD{xcd}"
                    yield Instance(
                        f"{prefix}_BM32_{suffix}{xsuf}",
                        "Gemm1CshuffleFn",
                        G1_INC,
                        G1_CSHUFFLE_PARAMS,
                        _g1_body(ne, h, e, 32, use_nt=use_nt, xcd_swizzle=xcd),
                    )

            # BM=128 cshuffle — enumerate XCD-swizzle variants. XCD=0 keeps the
            # legacy kernel-name (no _XCD suffix); positive XCD gets a suffix so
            # the dispatcher can pick among them.
            for xcd in BM128_XCD_SWIZZLES:
                suffix = "" if xcd == 0 else f"_XCD{xcd}"
                yield Instance(
                    f"{prefix}_BM128{suffix}",
                    "Gemm1CshuffleFn",
                    G1_INC,
                    G1_CSHUFFLE_PARAMS,
                    _g1_body(ne, h, e, 128, xcd_swizzle=xcd),
                )

            # BM=16 inline-quant. NT (bare name) is for the read-once regime
            # (M <= BM); the _CACHED flavor serves M > BM where B gets cross-CTA
            # reuse. Dispatch picks via the kernel-name suffix (CSV kernelName1).
            for use_nt, suffix in [(True, ""), (False, "_CACHED")]:
                for xcd in BM16_XCD_SWIZZLES:
                    xsuf = "" if xcd == 0 else f"_XCD{xcd}"
                    yield Instance(
                        f"{prefix}_BM16_INLINEQUANT{suffix}{xsuf}",
                        "Gemm1CshuffleFn",
                        G1_INC,
                        G1_CSHUFFLE_PARAMS,
                        _g1_body(ne, h, e, 16, use_nt=use_nt, inline_quant=True,
                                 xcd_swizzle=xcd),
                    )

    def enumerate_g2_instances(self):
        for ne, h, e, topk in SHAPES:
            prefix_topk = f"mxfp4_moe_g2_a4w4_NE{ne}_H{h}_E{e}_TOPK{topk}"
            prefix_nt   = f"mxfp4_moe_g2_a4w4_NE{ne}_H{h}_E{e}"

            # Each atomic variant comes in a cached (default) and a non-temporal
            # (_NT) B-load flavor. NT is a dispatch-level choice (the CSV kernelName2
            # carries the suffix); the default rule enables it for M <= BM. The
            # nonatomic BM=128 path stays cached (cross-CTA L1 reuse dominates).
            for use_nt, nt_suffix in [(False, ""), (True, "_NT")]:
                for bm in (16, 32, 64):
                    for xcd in BM32_XCD_SWIZZLES:   # {0,1,2}; reuse the small-tier set
                        xsuf = "" if xcd == 0 else f"_XCD{xcd}"
                        yield Instance(
                            f"{prefix_topk}_BM{bm}_ATOMIC{nt_suffix}{xsuf}",
                            "Gemm2AtomicFn",
                            G2_INC,
                            G2_ATOMIC_PARAMS,
                            _g2_atomic_body(ne, h, e, topk, bm, use_nt=use_nt,
                                            xcd_swizzle=xcd),
                        )

            # BM=128 nonatomic — enumerate XCD-swizzle variants (large-M target).
            for xcd in BM128_XCD_SWIZZLES:
                suffix = "" if xcd == 0 else f"_XCD{xcd}"
                yield Instance(
                    f"{prefix_nt}_BM128_NONATOMIC{suffix}",
                    "Gemm2NonatomicFn",
                    G2_INC,
                    G2_NONATOMIC_PARAMS,
                    _g2_nonatomic_body(ne, h, e, xcd_swizzle=xcd),
                )

    # -- emitters ------------------------------------------------------------
    def gen_instances(self, instances):
        inst_dir = self.working_path / "instances"
        inst_dir.mkdir(exist_ok=True)
        for inst in instances:
            text = INSTANCE_HEADER.format(
                kernel_include=inst.include,
                fn_name=inst.name,
                params=inst.params,
                body=inst.body,
            )
            (inst_dir / f"{inst.name}.cu").write_text(text)

    def gen_lookup(self, g1_list, g2_list):
        out = [LOOKUP_HEADER_HEAD]

        out.append("\n// gemm1 instances\n")
        for inst in g1_list:
            out.append(self._decl_extern_c(inst) + "\n")
        out.append("\n// gemm2 instances\n")
        for inst in g2_list:
            out.append(self._decl_extern_c(inst) + "\n")

        g1_cshuffle = [i.name for i in g1_list if i.fn_type == "Gemm1CshuffleFn"]
        g2_atomic   = [i.name for i in g2_list if i.fn_type == "Gemm2AtomicFn"]
        g2_nonatom  = [i.name for i in g2_list if i.fn_type == "Gemm2NonatomicFn"]

        self._emit_map(out, "GENERATE_G1_CSHUFFLE_LOOKUP_TABLE",  g1_cshuffle)
        self._emit_map(out, "GENERATE_G2_ATOMIC_LOOKUP_TABLE",    g2_atomic)
        self._emit_map(out, "GENERATE_G2_NONATOMIC_LOOKUP_TABLE", g2_nonatom)

        (self.working_path / "mxfp4_moe_gemm_lookup.h").write_text("".join(out))

    @staticmethod
    def _decl_extern_c(inst):
        return (f'extern "C" void {inst.name}(\n'
                f'    hipStream_t stream,\n{inst.params});')

    @staticmethod
    def _emit_map(out, macro, names):
        out.append(f"\n#define {macro}() \\\n")
        out.append("    { \\\n")
        for n in names:
            out.append(f'        {{"{n}", &{n}}}, \\\n')
        out.append("    }\n")

    # -- driver --------------------------------------------------------------
    def run(self):
        self.working_path.mkdir(parents=True, exist_ok=True)
        g1 = list(self.enumerate_g1_instances())
        g2 = list(self.enumerate_g2_instances())
        self.gen_instances(g1 + g2)
        self.gen_lookup(g1, g2)
        print(f"mxfp4_moe codegen: {len(g1)} g1 + {len(g2)} g2 = "
              f"{len(g1) + len(g2)} instances under {self.working_path}/instances/")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--working_path", required=True,
                    help="output directory (gets instances/ subdir + lookup.h)")
    args = ap.parse_args()
    mxfp4_moe_gemm_codegen(args.working_path).run()


if __name__ == "__main__":
    main()
