// !!! This is a file automatically generated by hipify!!!
// Copyright (c) 2026, Advanced Micro Devices, Inc. All rights reserved.
//
// HIP MX-FP8 grouped GEMM for MoE (Phase A — forward, NT layout, balanced).
//
// Reuses the production single-GEMM tile struct
//   GEMM_Tile_MXFP8_NT_256x256x128_16x16x128_4_WAVE_GFX950
// from csrc/grouped_gemm_mxfp8/kernels/gemm/gemm_mxfp8_kernel.h, wrapping it with
// a per-expert base-pointer dispatch on a flat grid.
//
// Layout contract (matches existing HIP single GEMM):
//   A:        [M_total, K]     fp8 e4m3,  contiguous rows
//   B:        [G, N, K]        fp8 e4m3,  NT (each expert's matrix is [N, K])
//   A_scale:  [M_total, K//32] uint8 e8m0 — preshuffled on launch
//   B_scale:  [G, N, K//32]    uint8 e8m0 — preshuffled on launch
//   C:        [M_total, N]     bf16 / fp16
//   group_offs: [G+1] int64    prefix sum of tokens-per-expert
//   block_to_expert: [total_tiles] int32  (host-computed flat-grid expert lookup)
//   tile_offs:       [G+1]     int32     prefix sum of tiles_per_expert
//
// Constraints (Phase A):
//   - trans_b == false (weights stored as [G, N, K])
//   - each M_g must be a multiple of 16 (scale preshuffle alignment)
//   - N, K already aligned to single-GEMM requirements (N%16==0, K%128==0, K>=384)
//
// Gate: correctness vs Triton tl.dot_scaled reference.

#include "mxfp8_gemm.h"

#include <ATen/ATen.h>
#include <ATen/hip/HIPContext.h>
#include <ATen/hip/impl/HIPStreamMasqueradingAsCUDA.h>
#include <hip/hip_runtime.h>
#include <torch/extension.h>

#include <cstdint>

namespace aiter {

// Variant of preshuffle_scale_16x4_kernel that handles scale_cols not
// multiple of 4 by zero-filling the tail columns. Output stride is
// cols_padded (= round_up(cols_real, 4)); unreachable rows/cols produce 0
// (e8m0 0x00 = 2^-127 ≈ 0 → effectively masks tail-K contribution).
template <typename InT, typename OutT>
__global__ void preshuffle_scale_16x4_padded_kernel(
    const InT *in_scale_ptr, OutT *out_scale_ptr,
    const int rows, const int cols_real, const int cols_padded) {
    const int tid = threadIdx.x;
    const int bid = blockIdx.x;

    const InT  *in_base  = in_scale_ptr  + bid * 16 * cols_real;
    OutT       *out_base = out_scale_ptr + bid * 16 * cols_padded;

    for (int i = 0; i < cols_padded / 4; ++i) {
        const int col_start = i * 4;
        const int col       = col_start + tid / 16;
        const int row       = tid % 16;
        OutT      val       = OutT(0);
        if (col < cols_real && (bid * 16 + row) < rows) {
            val = static_cast<OutT>(in_base[row * cols_real + col]);
        }
        out_base[i * 16 * 4 + tid] = val;
    }
}

// ─── Grouped kernel ───
//
// Wraps the existing 256x256x128 MX-FP8 single-GEMM kernel with per-expert
// base-pointer setup. Flat grid over total_tiles; block_to_expert[bid] gives
// the expert index and (bid - tile_offs[expert]) gives the per-expert local
// tile index which is then decomposed into (pid_m, pid_n).
//
// The compute body is copy-pasted from the single-GEMM kernel; the only delta
// is (a) base-pointer math with expert offset and (b) M boundary = M_g (not
// global m). Duplicating the body rather than refactoring to call-through
// avoids inlining surprises that could disturb the tight register pinning.

template <typename AType, typename BType, typename CType>
__global__ __launch_bounds__(256, 1) void grouped_gemm_mxfp8_kernel(
    const AType *__restrict__ a_ptr, const BType *__restrict__ b_ptr,
    const uint32_t *__restrict__ a_s_ptr, const uint32_t *__restrict__ b_s_ptr,
    CType *__restrict__ c_ptr,
    const int64_t *__restrict__ group_offs_ptr,     // [G+1] int64
    const int32_t *__restrict__ block_to_expert,    // [total_tiles] int32
    const int32_t *__restrict__ tile_offs_ptr,      // [G+1] int32 (tile prefix sum)
    const uint32_t n, const uint32_t k,
    const uint32_t tiles_n, const uint32_t scale_cols) {
#if !defined(__gfx950__)
    assert(false && "grouped_gemm_mxfp8 requires gfx950");
    return;
#else
    using GemmTile =
        GEMM_Tile_MXFP8_NT_256x256x128_16x16x128_4_WAVE_GFX950<AType, BType, CType, float>;

    // ── Flat-grid → (expert, pid_m, pid_n) ──
    const int32_t flat_bid = blockIdx.x;
    const int32_t expert_g = block_to_expert[flat_bid];
    const int32_t tile_base = tile_offs_ptr[expert_g];
    const int32_t local_tile = flat_bid - tile_base;

    // Within-expert swizzle (column-major chunks of WGM=8 across N like single kernel)
    const int32_t pid_m_l = local_tile / static_cast<int32_t>(tiles_n);
    const int32_t pid_n_l = local_tile % static_cast<int32_t>(tiles_n);
    const int32_t pid_m   = pid_m_l * static_cast<int32_t>(GemmTile::BLOCK_SIZE_M);
    const int32_t pid_n   = pid_n_l * static_cast<int32_t>(GemmTile::BLOCK_SIZE_N);

    // Per-expert extents.
    const int64_t m_start_g = group_offs_ptr[expert_g];
    const int64_t m_end_g   = group_offs_ptr[expert_g + 1];
    const uint32_t m_g      = static_cast<uint32_t>(m_end_g - m_start_g);

    // Out-of-range blocks early-exit (shouldn't happen with exact flat grid,
    // but defensive — tile_offs may round up).
    if (pid_m_l < 0 || pid_n_l < 0) return;
    if (pid_m >= static_cast<int32_t>(m_g) || pid_n >= static_cast<int32_t>(n)) return;

    GemmTile tile(threadIdx.x, m_g, n, k);
    tile.reserve_pinned_regs();

    const uint32_t lane_id = tile.lane_id;
    const uint32_t warp_id = tile.warp_id;
    const uint32_t warp_m  = tile.warp_m;
    const uint32_t warp_n  = tile.warp_n;

    using ASmem                       = typename GemmTile::ASmemSubtile;
    using BSmem                       = typename GemmTile::BSmemSubtile;
    using ASSmem                      = typename GemmTile::AScaleSmemSubtile;
    using BSSmem                      = typename GemmTile::BScaleSmemSubtile;
    constexpr size_t SMEM_DATA_BYTES  = sizeof(ASmem) * 2 * 4 + sizeof(BSmem) * 2 * 4;
    constexpr size_t SMEM_SCALE_BYTES = sizeof(ASSmem) * 2 * 4 + sizeof(BSSmem) * 2 * 4;
    __shared__ char  smem_buf[SMEM_DATA_BYTES + SMEM_SCALE_BYTES];
    auto            *a_smem_tile = reinterpret_cast<ASmem(*)[4]>(smem_buf);
    auto            *b_smem_tile = reinterpret_cast<BSmem(*)[4]>(smem_buf + sizeof(ASmem) * 2 * 4);
    auto            *a_s_smem_tile = reinterpret_cast<ASSmem(*)[4]>(smem_buf + SMEM_DATA_BYTES);
    auto            *b_s_smem_tile =
        reinterpret_cast<BSSmem(*)[4]>(smem_buf + SMEM_DATA_BYTES + sizeof(ASSmem) * 2 * 4);

    // ── Per-expert base pointers ──
    //   A rows: [m_start_g + pid_m, m_start_g + pid_m + 256]
    //   B rows: expert-g slice [g * N * K], then [pid_n, pid_n + 256]
    //   A_scale rows: [m_start_g + pid_m, ...] × scale_cols (preshuffled uint32)
    //   B_scale rows: g-slice + [pid_n, ...] × scale_cols
    const AType    *a_base_ptr   = a_ptr + (m_start_g + pid_m) * k;
    const BType    *b_base_ptr   = b_ptr + (static_cast<int64_t>(expert_g) * n + pid_n) * k;
    const uint32_t *a_s_base_ptr = a_s_ptr + (m_start_g + pid_m) * scale_cols;
    const uint32_t *b_s_base_ptr =
        b_s_ptr + (static_cast<int64_t>(expert_g) * n + pid_n) * scale_cols;

    uint32_t ldg_offsets[2];
    tile.compute_ldg_offsets(ldg_offsets, k);
    uint32_t sts_offsets[2];
    tile.compute_sts_offsets(sts_offsets);
    uint32_t lds_offsets[2];
    tile.compute_lds_offsets(lds_offsets);
    const uint32_t scale_ldg_offset = lane_id;
    const uint32_t scale_sts_offset = lane_id;
    const uint32_t scale_lds_offset = lane_id;

    // Remaining bytes: clip to this expert's row footprint for A/A_scale;
    // for B/B_scale the remaining is within this expert's [n, k] slab.
    const uint32_t  a_remaining  = (m_g - pid_m) * k * sizeof(AType);
    const uint32_t  b_remaining  = (n - pid_n) * k * sizeof(BType);
    const uint32_t  as_remaining = (m_g - pid_m) * scale_cols * sizeof(uint32_t);
    const uint32_t  bs_remaining = (n - pid_n) * scale_cols * sizeof(uint32_t);
    const BufferSRD a_srd(a_base_ptr, a_remaining);
    const BufferSRD b_srd(b_base_ptr, b_remaining);
    const BufferSRD a_s_srd(a_s_base_ptr, as_remaining);
    const BufferSRD b_s_srd(b_s_base_ptr, bs_remaining);

    constexpr int32_t DATA_STRIDE  = GemmTile::BLOCK_SIZE_K;
    constexpr int32_t SCALE_STRIDE = GemmTile::SCALE_FRAG_SIZE * sizeof(uint32_t);

    // ── Prologue: preload tiles 0 and 1 into double-buffered SMEM ──
    tile.template load_a_gmem_to_smem_half_srd<0>(a_srd, ldg_offsets, a_smem_tile[0], sts_offsets);
    tile.template load_a_gmem_to_smem_half_srd<1>(a_srd, ldg_offsets, a_smem_tile[0], sts_offsets);
    tile.template load_b_gmem_to_smem_half_srd<0>(b_srd, ldg_offsets, b_smem_tile[0], sts_offsets);
    tile.template load_b_gmem_to_smem_half_srd<1>(b_srd, ldg_offsets, b_smem_tile[0], sts_offsets);
    tile.template load_a_scale_gmem_to_smem_half_srd<0>(a_s_srd, scale_ldg_offset, a_s_smem_tile[0],
                                                        scale_sts_offset, scale_cols);
    tile.template load_a_scale_gmem_to_smem_half_srd<1>(a_s_srd, scale_ldg_offset, a_s_smem_tile[0],
                                                        scale_sts_offset, scale_cols);
    tile.template load_b_scale_gmem_to_smem_half_srd<0>(b_s_srd, scale_ldg_offset, b_s_smem_tile[0],
                                                        scale_sts_offset, scale_cols);
    tile.template load_b_scale_gmem_to_smem_half_srd<1>(b_s_srd, scale_ldg_offset, b_s_smem_tile[0],
                                                        scale_sts_offset, scale_cols);

    tile.template load_a_gmem_to_smem_half_srd<0>(a_srd, ldg_offsets, a_smem_tile[1], sts_offsets,
                                                  DATA_STRIDE);
    tile.template load_a_gmem_to_smem_half_srd<1>(a_srd, ldg_offsets, a_smem_tile[1], sts_offsets,
                                                  DATA_STRIDE);
    tile.template load_b_gmem_to_smem_half_srd<0>(b_srd, ldg_offsets, b_smem_tile[1], sts_offsets,
                                                  DATA_STRIDE);
    tile.template load_b_gmem_to_smem_half_srd<1>(b_srd, ldg_offsets, b_smem_tile[1], sts_offsets,
                                                  DATA_STRIDE);
    tile.template load_a_scale_gmem_to_smem_half_srd<0>(a_s_srd, scale_ldg_offset, a_s_smem_tile[1],
                                                        scale_sts_offset, scale_cols, SCALE_STRIDE);
    tile.template load_a_scale_gmem_to_smem_half_srd<1>(a_s_srd, scale_ldg_offset, a_s_smem_tile[1],
                                                        scale_sts_offset, scale_cols, SCALE_STRIDE);
    tile.template load_b_scale_gmem_to_smem_half_srd<0>(b_s_srd, scale_ldg_offset, b_s_smem_tile[1],
                                                        scale_sts_offset, scale_cols, SCALE_STRIDE);
    tile.template load_b_scale_gmem_to_smem_half_srd<1>(b_s_srd, scale_ldg_offset, b_s_smem_tile[1],
                                                        scale_sts_offset, scale_cols, SCALE_STRIDE);

    tile.zero_c_agpr();
    wait_vmcnt<0>();
    __builtin_amdgcn_s_barrier();

    uint32_t       cur     = 0;
    uint32_t       next    = 1;
    const uint32_t k_iters = (k + GemmTile::BLOCK_SIZE_K - 1) / GemmTile::BLOCK_SIZE_K;

    // Prologue: LDS for A0/B0 into pinned regs
    GemmTile::template load_data_subtile_pinned<GemmTile::PIN_A0>(
        a_smem_tile[cur][warp_m].u32_ptr(), lds_offsets);
    GemmTile::template load_scale_subtile_pinned<GemmTile::PIN_AS0>(
        a_s_smem_tile[cur][warp_m].u32_ptr(), scale_lds_offset);
    GemmTile::template load_data_subtile_pinned<GemmTile::PIN_B0>(
        b_smem_tile[cur][warp_n].u32_ptr(), lds_offsets);
    GemmTile::template load_scale_subtile_pinned<GemmTile::PIN_BS0>(
        b_s_smem_tile[cur][warp_n].u32_ptr(), scale_lds_offset);

    if (k_iters > 2) {
        tile.template load_a_gmem_to_smem_half_srd<0>(a_srd, ldg_offsets, a_smem_tile[cur],
                                                      sts_offsets, 2 * DATA_STRIDE);
        tile.template load_a_scale_gmem_to_smem_half_srd<0>(a_s_srd, scale_ldg_offset,
                                                            a_s_smem_tile[cur], scale_sts_offset,
                                                            scale_cols, 2 * SCALE_STRIDE);
        tile.template load_b_gmem_to_smem_half_srd<0>(b_srd, ldg_offsets, b_smem_tile[cur],
                                                      sts_offsets, 2 * DATA_STRIDE);
        tile.template load_b_scale_gmem_to_smem_half_srd<0>(b_s_srd, scale_ldg_offset,
                                                            b_s_smem_tile[cur], scale_sts_offset,
                                                            scale_cols, 2 * SCALE_STRIDE);
    }
    wait_lgkmcnt<0>();

    int32_t base_data_soff[4], base_scale_soff[4];
    tile.precompute_base_soff(base_data_soff, base_scale_soff, scale_cols);

    const uint32_t sts_wb =
        __builtin_amdgcn_readfirstlane(warp_id * GemmTile::MFMA_SIZE_M * GemmTile::MFMA_SIZE_K);
    const uint32_t s_smem_off = __builtin_amdgcn_readfirstlane((warp_id * 64 + scale_sts_offset) *
                                                               (uint32_t) sizeof(uint32_t));
    const uint32_t scale_gmem_byte_off = scale_ldg_offset * (uint32_t) sizeof(uint32_t);

    // ── Main loop ──
    const uint32_t main_iters = k_iters > 3 ? k_iters - 3 : 0;
    int32_t        data_off = 2 * DATA_STRIDE, scale_off = 2 * SCALE_STRIDE;
    for (uint32_t ki = 0; ki < main_iters;
         ++ki, data_off += DATA_STRIDE, scale_off += SCALE_STRIDE) {
        const int32_t next_data_off  = data_off + DATA_STRIDE;
        const int32_t next_scale_off = scale_off + SCALE_STRIDE;

        {
            uint32_t dm0_0 = __builtin_amdgcn_readfirstlane(b_smem_tile[cur][2].u32_ptr()) + sts_wb;
            uint32_t dm0_1 = __builtin_amdgcn_readfirstlane(b_smem_tile[cur][3].u32_ptr()) + sts_wb;
            uint32_t sm0_0 =
                __builtin_amdgcn_readfirstlane(b_s_smem_tile[cur][2].u32_ptr()) + s_smem_off;
            uint32_t sm0_1 =
                __builtin_amdgcn_readfirstlane(b_s_smem_tile[cur][3].u32_ptr()) + s_smem_off;
            GemmTile::template phase_mfma_lds_ldg<GemmTile::PIN_A0, GemmTile::PIN_AS0,
                                                  GemmTile::PIN_B0, GemmTile::PIN_BS0, 0, 0,
                                                  GemmTile::PIN_B1, GemmTile::PIN_BS1>(
                b_smem_tile[cur][warp_n + 2].u32_ptr(), lds_offsets,
                b_s_smem_tile[cur][warp_n + 2].u32_ptr(), scale_lds_offset, b_srd, ldg_offsets,
                dm0_0, dm0_1, base_data_soff[2] + data_off, base_data_soff[3] + data_off, b_s_srd,
                scale_gmem_byte_off, sm0_0, sm0_1, base_scale_soff[2] + scale_off,
                base_scale_soff[3] + scale_off);
        }
        {
            uint32_t dm0_0 = __builtin_amdgcn_readfirstlane(a_smem_tile[cur][2].u32_ptr()) + sts_wb;
            uint32_t dm0_1 = __builtin_amdgcn_readfirstlane(a_smem_tile[cur][3].u32_ptr()) + sts_wb;
            uint32_t sm0_0 =
                __builtin_amdgcn_readfirstlane(a_s_smem_tile[cur][2].u32_ptr()) + s_smem_off;
            uint32_t sm0_1 =
                __builtin_amdgcn_readfirstlane(a_s_smem_tile[cur][3].u32_ptr()) + s_smem_off;
            GemmTile::template phase_mfma_lds_ldg<GemmTile::PIN_A0, GemmTile::PIN_AS0,
                                                  GemmTile::PIN_B1, GemmTile::PIN_BS1, 0, 1,
                                                  GemmTile::PIN_A1, GemmTile::PIN_AS1>(
                a_smem_tile[cur][warp_m + 2].u32_ptr(), lds_offsets,
                a_s_smem_tile[cur][warp_m + 2].u32_ptr(), scale_lds_offset, a_srd, ldg_offsets,
                dm0_0, dm0_1, base_data_soff[2] + data_off, base_data_soff[3] + data_off, a_s_srd,
                scale_gmem_byte_off, sm0_0, sm0_1, base_scale_soff[2] + scale_off,
                base_scale_soff[3] + scale_off);
        }
        {
            uint32_t dm0_0 =
                __builtin_amdgcn_readfirstlane(a_smem_tile[next][0].u32_ptr()) + sts_wb;
            uint32_t dm0_1 =
                __builtin_amdgcn_readfirstlane(a_smem_tile[next][1].u32_ptr()) + sts_wb;
            uint32_t sm0_0 =
                __builtin_amdgcn_readfirstlane(a_s_smem_tile[next][0].u32_ptr()) + s_smem_off;
            uint32_t sm0_1 =
                __builtin_amdgcn_readfirstlane(a_s_smem_tile[next][1].u32_ptr()) + s_smem_off;
            GemmTile::template phase_mfma_lds_ldg<GemmTile::PIN_A1, GemmTile::PIN_AS1,
                                                  GemmTile::PIN_B0, GemmTile::PIN_BS0, 1, 0,
                                                  GemmTile::PIN_A0, GemmTile::PIN_AS0>(
                a_smem_tile[next][warp_m].u32_ptr(), lds_offsets,
                a_s_smem_tile[next][warp_m].u32_ptr(), scale_lds_offset, a_srd, ldg_offsets, dm0_0,
                dm0_1, base_data_soff[0] + next_data_off, base_data_soff[1] + next_data_off,
                a_s_srd, scale_gmem_byte_off, sm0_0, sm0_1, base_scale_soff[0] + next_scale_off,
                base_scale_soff[1] + next_scale_off);
        }
        {
            uint32_t dm0_0 =
                __builtin_amdgcn_readfirstlane(b_smem_tile[next][0].u32_ptr()) + sts_wb;
            uint32_t dm0_1 =
                __builtin_amdgcn_readfirstlane(b_smem_tile[next][1].u32_ptr()) + sts_wb;
            uint32_t sm0_0 =
                __builtin_amdgcn_readfirstlane(b_s_smem_tile[next][0].u32_ptr()) + s_smem_off;
            uint32_t sm0_1 =
                __builtin_amdgcn_readfirstlane(b_s_smem_tile[next][1].u32_ptr()) + s_smem_off;
            GemmTile::template phase_mfma_lds_ldg<GemmTile::PIN_A1, GemmTile::PIN_AS1,
                                                  GemmTile::PIN_B1, GemmTile::PIN_BS1, 1, 1,
                                                  GemmTile::PIN_B0, GemmTile::PIN_BS0>(
                b_smem_tile[next][warp_n].u32_ptr(), lds_offsets,
                b_s_smem_tile[next][warp_n].u32_ptr(), scale_lds_offset, b_srd, ldg_offsets, dm0_0,
                dm0_1, base_data_soff[0] + next_data_off, base_data_soff[1] + next_data_off,
                b_s_srd, scale_gmem_byte_off, sm0_0, sm0_1, base_scale_soff[0] + next_scale_off,
                base_scale_soff[1] + next_scale_off);
        }

        wait_vmcnt<12>();
        __builtin_amdgcn_s_barrier();
        cur ^= 1;
        next ^= 1;
    }

    // ── Epilogue 1 ──
    {
        {
            uint32_t dm0_0 = __builtin_amdgcn_readfirstlane(b_smem_tile[cur][2].u32_ptr()) + sts_wb;
            uint32_t dm0_1 = __builtin_amdgcn_readfirstlane(b_smem_tile[cur][3].u32_ptr()) + sts_wb;
            uint32_t sm0_0 =
                __builtin_amdgcn_readfirstlane(b_s_smem_tile[cur][2].u32_ptr()) + s_smem_off;
            uint32_t sm0_1 =
                __builtin_amdgcn_readfirstlane(b_s_smem_tile[cur][3].u32_ptr()) + s_smem_off;
            GemmTile::template phase_mfma_lds_ldg<GemmTile::PIN_A0, GemmTile::PIN_AS0,
                                                  GemmTile::PIN_B0, GemmTile::PIN_BS0, 0, 0,
                                                  GemmTile::PIN_B1, GemmTile::PIN_BS1>(
                b_smem_tile[cur][warp_n + 2].u32_ptr(), lds_offsets,
                b_s_smem_tile[cur][warp_n + 2].u32_ptr(), scale_lds_offset, b_srd, ldg_offsets,
                dm0_0, dm0_1, base_data_soff[2] + data_off, base_data_soff[3] + data_off, b_s_srd,
                scale_gmem_byte_off, sm0_0, sm0_1, base_scale_soff[2] + scale_off,
                base_scale_soff[3] + scale_off);
        }
        {
            uint32_t dm0_0 = __builtin_amdgcn_readfirstlane(a_smem_tile[cur][2].u32_ptr()) + sts_wb;
            uint32_t dm0_1 = __builtin_amdgcn_readfirstlane(a_smem_tile[cur][3].u32_ptr()) + sts_wb;
            uint32_t sm0_0 =
                __builtin_amdgcn_readfirstlane(a_s_smem_tile[cur][2].u32_ptr()) + s_smem_off;
            uint32_t sm0_1 =
                __builtin_amdgcn_readfirstlane(a_s_smem_tile[cur][3].u32_ptr()) + s_smem_off;
            GemmTile::template phase_mfma_lds_ldg<GemmTile::PIN_A0, GemmTile::PIN_AS0,
                                                  GemmTile::PIN_B1, GemmTile::PIN_BS1, 0, 1,
                                                  GemmTile::PIN_A1, GemmTile::PIN_AS1>(
                a_smem_tile[cur][warp_m + 2].u32_ptr(), lds_offsets,
                a_s_smem_tile[cur][warp_m + 2].u32_ptr(), scale_lds_offset, a_srd, ldg_offsets,
                dm0_0, dm0_1, base_data_soff[2] + data_off, base_data_soff[3] + data_off, a_s_srd,
                scale_gmem_byte_off, sm0_0, sm0_1, base_scale_soff[2] + scale_off,
                base_scale_soff[3] + scale_off);
        }
        GemmTile::template phase_mfma_lds<GemmTile::PIN_A1, GemmTile::PIN_AS1, GemmTile::PIN_B0,
                                          GemmTile::PIN_BS0, 1, 0, GemmTile::PIN_A0,
                                          GemmTile::PIN_AS0>(
            a_smem_tile[next][warp_m].u32_ptr(), lds_offsets, a_s_smem_tile[next][warp_m].u32_ptr(),
            scale_lds_offset);
        GemmTile::template phase_mfma_lds<GemmTile::PIN_A1, GemmTile::PIN_AS1, GemmTile::PIN_B1,
                                          GemmTile::PIN_BS1, 1, 1, GemmTile::PIN_B0,
                                          GemmTile::PIN_BS0>(
            b_smem_tile[next][warp_n].u32_ptr(), lds_offsets, b_s_smem_tile[next][warp_n].u32_ptr(),
            scale_lds_offset);
        wait_vmcnt<6>();
        __builtin_amdgcn_s_barrier();
        cur ^= 1;
        next ^= 1;
    }

    // ── Epilogue 2 ──
    {
        GemmTile::template phase_mfma_lds<GemmTile::PIN_A0, GemmTile::PIN_AS0, GemmTile::PIN_B0,
                                          GemmTile::PIN_BS0, 0, 0, GemmTile::PIN_B1,
                                          GemmTile::PIN_BS1>(
            b_smem_tile[cur][warp_n + 2].u32_ptr(), lds_offsets,
            b_s_smem_tile[cur][warp_n + 2].u32_ptr(), scale_lds_offset);
        GemmTile::template phase_mfma_lds<GemmTile::PIN_A0, GemmTile::PIN_AS0, GemmTile::PIN_B1,
                                          GemmTile::PIN_BS1, 0, 1, GemmTile::PIN_A1,
                                          GemmTile::PIN_AS1>(
            a_smem_tile[cur][warp_m + 2].u32_ptr(), lds_offsets,
            a_s_smem_tile[cur][warp_m + 2].u32_ptr(), scale_lds_offset);
        wait_vmcnt<0>();
        __builtin_amdgcn_s_barrier();
        GemmTile::template phase_mfma_lds<GemmTile::PIN_A1, GemmTile::PIN_AS1, GemmTile::PIN_B0,
                                          GemmTile::PIN_BS0, 1, 0, GemmTile::PIN_A0,
                                          GemmTile::PIN_AS0>(
            a_smem_tile[next][warp_m].u32_ptr(), lds_offsets, a_s_smem_tile[next][warp_m].u32_ptr(),
            scale_lds_offset);
        GemmTile::template phase_mfma_lds<GemmTile::PIN_A1, GemmTile::PIN_AS1, GemmTile::PIN_B1,
                                          GemmTile::PIN_BS1, 1, 1, GemmTile::PIN_B0,
                                          GemmTile::PIN_BS0>(
            b_smem_tile[next][warp_n].u32_ptr(), lds_offsets, b_s_smem_tile[next][warp_n].u32_ptr(),
            scale_lds_offset);
        cur ^= 1;
        next ^= 1;
    }

    // ── Epilogue 3 ──
    {
        GemmTile::template phase_mfma_lds<GemmTile::PIN_A0, GemmTile::PIN_AS0, GemmTile::PIN_B0,
                                          GemmTile::PIN_BS0, 0, 0, GemmTile::PIN_B1,
                                          GemmTile::PIN_BS1>(
            b_smem_tile[cur][warp_n + 2].u32_ptr(), lds_offsets,
            b_s_smem_tile[cur][warp_n + 2].u32_ptr(), scale_lds_offset);
        GemmTile::template phase_mfma_lds<GemmTile::PIN_A0, GemmTile::PIN_AS0, GemmTile::PIN_B1,
                                          GemmTile::PIN_BS1, 0, 1, GemmTile::PIN_A1,
                                          GemmTile::PIN_AS1>(
            a_smem_tile[cur][warp_m + 2].u32_ptr(), lds_offsets,
            a_s_smem_tile[cur][warp_m + 2].u32_ptr(), scale_lds_offset);
        GemmTile::template phase_mfma_only<GemmTile::PIN_A1, GemmTile::PIN_AS1, GemmTile::PIN_B0,
                                           GemmTile::PIN_BS0, 1, 0>();
        GemmTile::template phase_mfma_only<GemmTile::PIN_A1, GemmTile::PIN_AS1, GemmTile::PIN_B1,
                                           GemmTile::PIN_BS1, 1, 1>();
    }

    // ── Store C ──
    __builtin_amdgcn_sched_barrier(0);
    uint32_t c_stg_offsets[4];
    tile.compute_stg_offsets(c_stg_offsets);
    CType *c_stg_base_ptr =
        c_ptr + (m_start_g + pid_m) * n + pid_n + warp_id / 2 * 64 * n + warp_id % 2 * 64;
    const bool is_boundary_tile =
        (pid_m + 256 > static_cast<int32_t>(m_g)) || (pid_n + 256 > static_cast<int32_t>(n));

    if (!is_boundary_tile) {
        float32x4 c_tmp[4][4];
        tile.template read_c_subtile_from_agpr<0, 0>(c_tmp);
        tile.store_c_subtile(c_stg_base_ptr + 0 * 128 * n + 0 * 128, n, c_tmp, c_stg_offsets);
        tile.template read_c_subtile_from_agpr<0, 1>(c_tmp);
        tile.store_c_subtile(c_stg_base_ptr + 0 * 128 * n + 1 * 128, n, c_tmp, c_stg_offsets);
        tile.template read_c_subtile_from_agpr<1, 0>(c_tmp);
        tile.store_c_subtile(c_stg_base_ptr + 1 * 128 * n + 0 * 128, n, c_tmp, c_stg_offsets);
        tile.template read_c_subtile_from_agpr<1, 1>(c_tmp);
        tile.store_c_subtile(c_stg_base_ptr + 1 * 128 * n + 1 * 128, n, c_tmp, c_stg_offsets);
    } else {
        const int32_t warp_base_m  = warp_id / 2 * 64;
        const int32_t warp_base_n  = warp_id % 2 * 64;
        const int32_t tile_valid_m = min(static_cast<int32_t>(m_g) - pid_m, 256) - warp_base_m;
        const int32_t tile_valid_n = min(static_cast<int32_t>(n) - pid_n, 256) - warp_base_n;
        float32x4     c_tmp[4][4];
        tile.template read_c_subtile_from_agpr<0, 0>(c_tmp);
        tile.store_c_subtile(c_stg_base_ptr + 0 * 128 * n + 0 * 128, n, c_tmp, c_stg_offsets,
                             tile_valid_m, tile_valid_n);
        tile.template read_c_subtile_from_agpr<0, 1>(c_tmp);
        tile.store_c_subtile(c_stg_base_ptr + 0 * 128 * n + 1 * 128, n, c_tmp, c_stg_offsets,
                             tile_valid_m, tile_valid_n - 128);
        tile.template read_c_subtile_from_agpr<1, 0>(c_tmp);
        tile.store_c_subtile(c_stg_base_ptr + 1 * 128 * n + 0 * 128, n, c_tmp, c_stg_offsets,
                             tile_valid_m - 128, tile_valid_n);
        tile.template read_c_subtile_from_agpr<1, 1>(c_tmp);
        tile.store_c_subtile(c_stg_base_ptr + 1 * 128 * n + 1 * 128, n, c_tmp, c_stg_offsets,
                             tile_valid_m - 128, tile_valid_n - 128);
    }
#endif
}

// ─── Host launcher ───
template <typename AType, typename BType, typename CType>
static void launch_grouped_mxfp8(
    const AType *a_ptr, const BType *b_ptr,
    const dtype::float8_e8m0 *a_scale_ptr,
    const dtype::float8_e8m0 *b_scale_ptr,
    CType *c_ptr,
    const int64_t *group_offs_ptr,      // [G+1]
    const int32_t *block_to_expert_ptr, // [total_tiles]
    const int32_t *tile_offs_ptr,       // [G+1]
    int32_t m_total, int32_t n, int32_t k, int32_t g, int32_t total_tiles,
    void *workspace, size_t workspace_size,
    hipStream_t stream) {
    constexpr int32_t MX_BLOCK_SIZE = 32;
    const int32_t     scale_cols        = (k + MX_BLOCK_SIZE - 1) / MX_BLOCK_SIZE;
    // Round up to multiple of 4 — preshuffle operates on 16x4 blocks; padding
    // cols are zero-filled (e8m0 0 ≈ 2^-127 → tail-K contribution ~= 0).
    const int32_t     scale_cols_padded = (scale_cols + 3) & ~3;
    const size_t      a_scale_bytes =
        (size_t) m_total * scale_cols_padded * sizeof(uint32_t);

    auto *a_scale_preshuf = reinterpret_cast<uint32_t *>(workspace);
    auto *b_scale_preshuf =
        reinterpret_cast<uint32_t *>(reinterpret_cast<uint8_t *>(workspace) + a_scale_bytes);

    auto *a_scale_raw = reinterpret_cast<const uint8_t *>(a_scale_ptr);
    auto *b_scale_raw = reinterpret_cast<const uint8_t *>(b_scale_ptr);

    // Preshuffle A scales using padded variant (handles scale_cols % 4 != 0).
   hipLaunchKernelGGL(( preshuffle_scale_16x4_padded_kernel<uint8_t, uint32_t>)
        , dim3(m_total / 16), dim3(64), 0, stream, a_scale_raw, a_scale_preshuf, m_total,
                                          scale_cols, scale_cols_padded);

    // B scales [G, N, scale_cols] flattened to [G*N, scale_cols]. N%16 required.
   hipLaunchKernelGGL(( preshuffle_scale_16x4_padded_kernel<uint8_t, uint32_t>)
        , dim3((g * n) / 16), dim3(64), 0, stream, b_scale_raw, b_scale_preshuf, g * n,
                                          scale_cols, scale_cols_padded);

    const uint32_t tiles_n = (n + 255) / 256;

    dim3 grid(total_tiles);
    dim3 block(256);
   hipLaunchKernelGGL(( grouped_gemm_mxfp8_kernel<AType, BType, CType>)
        , dim3(grid), dim3(block), 0, stream, a_ptr, b_ptr, a_scale_preshuf, b_scale_preshuf, c_ptr,
                                     group_offs_ptr, block_to_expert_ptr, tile_offs_ptr,
                                     static_cast<uint32_t>(n), static_cast<uint32_t>(k),
                                     tiles_n, static_cast<uint32_t>(scale_cols_padded));
}

static size_t grouped_mxfp8_workspace_size(int32_t m_total, int32_t n, int32_t k, int32_t g) {
    constexpr int32_t MX_BLOCK_SIZE = 32;
    const int32_t     scale_cols    = (k + MX_BLOCK_SIZE - 1) / MX_BLOCK_SIZE;
    const int32_t     scale_cols_padded = (scale_cols + 3) & ~3;
    return (size_t) m_total * scale_cols_padded * sizeof(uint32_t) +
           (size_t) g * n * scale_cols_padded * sizeof(uint32_t);
}

// ─── PyTorch binding ───

at::Tensor grouped_gemm_mxfp8_hip_fwd(at::Tensor a, at::Tensor b, at::Tensor a_scale,
                                      at::Tensor b_scale, at::Tensor group_offs,
                                      at::Tensor block_to_expert, at::Tensor tile_offs,
                                      at::ScalarType out_dtype) {
    TORCH_CHECK(a.is_contiguous() && b.is_contiguous());
    TORCH_CHECK(a_scale.is_contiguous() && b_scale.is_contiguous());
    TORCH_CHECK(a.dim() == 2, "a must be [M_total, K]");
    TORCH_CHECK(b.dim() == 3, "b must be [G, N, K] (NT)");
    TORCH_CHECK(a.scalar_type() == at::kFloat8_e4m3fn, "only e4m3 for Phase A");
    TORCH_CHECK(b.scalar_type() == at::kFloat8_e4m3fn, "only e4m3 for Phase A");
    TORCH_CHECK(a_scale.scalar_type() == at::kFloat8_e8m0fnu, "a_scale must be e8m0");
    TORCH_CHECK(b_scale.scalar_type() == at::kFloat8_e8m0fnu, "b_scale must be e8m0");
    TORCH_CHECK(group_offs.scalar_type() == at::kLong, "group_offs must be int64");
    TORCH_CHECK(block_to_expert.scalar_type() == at::kInt, "block_to_expert must be int32");
    TORCH_CHECK(tile_offs.scalar_type() == at::kInt, "tile_offs must be int32");

    const int64_t m_total = a.size(0);
    const int64_t k       = a.size(1);
    const int64_t g       = b.size(0);
    const int64_t n       = b.size(1);
    TORCH_CHECK(b.size(2) == k, "K mismatch");
    // The kernel uses BLOCK_SIZE_K=128 ceil-div iters; BufferSRD returns 0 for
    // out-of-bounds reads of A/B data, and scale bytes loaded from OOB are 0
    // (e8m0 0x00 = 2^-127 ≈ 0), so tail-K <128 contributes ~0 via scale=0.
    // Still require K be multiple of 32 (the MX scale group) and K >= 384
    // to ensure >=3 full iters (prologue/main/epilogue pipeline assumes it).
    TORCH_CHECK(k % 32 == 0, "K must be multiple of 32 (MX scale group)");
    TORCH_CHECK(k >= 384, "K must be >= 384 (kernel pipeline minimum)");
    TORCH_CHECK(n % 16 == 0, "N must be multiple of 16");
    TORCH_CHECK(group_offs.numel() == g + 1, "group_offs size must be G+1");
    TORCH_CHECK(tile_offs.numel() == g + 1, "tile_offs size must be G+1");

    const int64_t total_tiles = block_to_expert.numel();

    at::Tensor c = at::empty({m_total, n},
                             at::TensorOptions().dtype(out_dtype).device(a.device()));

    const size_t ws = grouped_mxfp8_workspace_size(m_total, n, k, g);
    at::Tensor   workspace =
        at::empty({(int64_t) ws}, at::TensorOptions().dtype(at::kByte).device(a.device()));

    auto stream = at::hip::getCurrentHIPStreamMasqueradingAsCUDA();

#define LAUNCH(CType)                                                                              \
    launch_grouped_mxfp8<aiter::dtype::float8_e4m3, aiter::dtype::float8_e4m3,       \
                         CType>(                                                                   \
        reinterpret_cast<const aiter::dtype::float8_e4m3 *>(a.data_ptr()),                  \
        reinterpret_cast<const aiter::dtype::float8_e4m3 *>(b.data_ptr()),                  \
        reinterpret_cast<const aiter::dtype::float8_e8m0 *>(a_scale.data_ptr()),            \
        reinterpret_cast<const aiter::dtype::float8_e8m0 *>(b_scale.data_ptr()),            \
        reinterpret_cast<CType *>(c.data_ptr()), group_offs.data_ptr<int64_t>(),                   \
        block_to_expert.data_ptr<int32_t>(), tile_offs.data_ptr<int32_t>(),                        \
        static_cast<int32_t>(m_total), static_cast<int32_t>(n), static_cast<int32_t>(k),           \
        static_cast<int32_t>(g), static_cast<int32_t>(total_tiles), workspace.data_ptr(), ws,      \
        stream)

    if (out_dtype == at::kBFloat16) {
        LAUNCH(aiter::dtype::bfloat16);
    } else if (out_dtype == at::kHalf) {
        LAUNCH(aiter::dtype::float16);
    } else {
        TORCH_CHECK(false, "out_dtype must be bf16 or fp16");
    }
#undef LAUNCH

    return c;
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("grouped_gemm_mxfp8_hip_fwd", &grouped_gemm_mxfp8_hip_fwd,
          "HIP MX-FP8 grouped GEMM forward (NT, balanced MoE, Phase A)");
}

} // namespace aiter
