# SPDX-License-Identifier: MIT
# Copyright (C) 2024-2026, Advanced Micro Devices, Inc. All rights reserved.

"""Attention config loading: the shape-key formatter and the tier walk that
lets a *measured* MHA forward tile beat the hand-authored feature default.

Attention used to have no family module because its lookup was a single
feature-bucket read with no selection logic, which configs/CLAUDE.md says is
better left as two lines against the core. Tuning changes that: a winner is
specific to a GPU and a shape, so the family now needs the same kind of walk
conv has, and that walk needs one home.

The table lives inside the family's existing file under ``fwd.shapes`` rather
than in per-shape files, so publishing a thousand tuned shapes adds a thousand
entries to one reviewable document instead of a thousand paths to the tree:

    fwd:
      shapes:                        # generated by the tuner, kept sorted
        "cu=304,model=mi325x":
          "mode=varlen,hdq=192,...": {BLOCK_M: 128, ...}
        "any":
          "mode=varlen,hdq=192,...": {BLOCK_M: 64, ...}
      default: {...}                 # hand-authored feature tiers, unchanged
      pe: {...}

A file with no ``shapes`` key resolves exactly as it did before this module
existed, so an untuned family keeps its current behaviour to the byte.
"""

import functools

from aiter.ops.triton.utils._triton import arch_info
from aiter.ops.triton.utils.config_utils import (
    HARDWARE_ANY,
    USE_LRU_CACHE,
    format_hardware_key,
    load_config_json_merged,
    resolve_config_relpath,
)
from aiter.ops.triton.utils.logger import AiterTritonLogger

logger = AiterTritonLogger()

__all__ = [
    "MHA_CONFIG_NAME",
    "current_mha_hardware_key",
    "format_mha_shape_key",
    "get_mha_config",
    "mha_config_relpath",
    "mha_seqlen_bucket",
]

MHA_CONFIG_NAME = "MHA"

# The two backends spell their family file differently; the tree layout is
# otherwise identical, so the difference is confined to this table.
_MHA_CONFIG_FILENAME = {"triton": "DEFAULT.json", "gluon": "mha.json"}


def mha_config_relpath(backend: str, arch: str | None = None) -> str:
    """Path to one backend's MHA family file, relative to a config root."""
    if backend not in _MHA_CONFIG_FILENAME:
        raise ValueError(
            f"unknown MHA config backend {backend!r}; "
            f"expected one of {sorted(_MHA_CONFIG_FILENAME)}"
        )
    directory = resolve_config_relpath(
        "attention", MHA_CONFIG_NAME, backend, arch or arch_info.get_arch()
    )
    return f"{directory}/{_MHA_CONFIG_FILENAME[backend]}"


def mha_seqlen_bucket(seqlen: int) -> int:
    """Round a sequence length up to the next power of two.

    Attention tile choice tracks the order of magnitude of the context, not
    its exact token count. Bucketing is what makes a tuned entry reusable: a
    table keyed on a literal 42700 tokens only ever matches the benchmark that
    produced it, while the 65536 bucket also covers the next request.
    """
    value = max(16, int(seqlen))
    return 1 << (value - 1).bit_length()


def format_mha_shape_key(
    *,
    mode: str,
    hdim_q: int,
    hdim_v: int,
    nhead_q: int,
    nhead_k: int,
    dtype: str,
    causal: bool,
    max_seqlen_q: int,
    max_seqlen_k: int,
) -> str:
    """Canonical key for one tuned MHA forward shape.

    Built here and only here, by both the loader and the tuner's writer, so a
    key can never be spelled two ways and go silently unmatched.
    """
    return (
        f"mode={str(mode).lower()},"
        f"hdq={int(hdim_q)},hdv={int(hdim_v)},"
        f"hq={int(nhead_q)},hk={int(nhead_k)},"
        f"dt={str(dtype).removeprefix('torch.').lower()},"
        f"causal={int(bool(causal))},"
        f"sq={mha_seqlen_bucket(max_seqlen_q)},"
        f"sk={mha_seqlen_bucket(max_seqlen_k)}"
    )


@functools.lru_cache(maxsize=1 if USE_LRU_CACHE else 0)
def current_mha_hardware_key() -> str:
    """Hardware tier key for the running GPU, or the SKU-agnostic fallback.

    A machine that cannot report its SKU still reads tuned entries -- it just
    reads the ones that were published without a SKU.
    """
    try:
        import torch

        from aiter.jit.utils.chip_info import get_gpu_model

        device = torch.cuda.current_device()
        return format_hardware_key(
            torch.cuda.get_device_properties(device).multi_processor_count,
            get_gpu_model(device),
        )
    except Exception as error:  # noqa: BLE001 - identity is best-effort
        logger.debug(f"MHA hardware key unavailable ({error}); using {HARDWARE_ANY}")
        return HARDWARE_ANY


def get_mha_config(
    backend: str,
    feature_bucket: str,
    shape_key: str | None = None,
) -> dict:
    """Load one MHA forward config, preferring a measured entry.

    Walk order, first hit wins:

    1. ``shapes[<this GPU>][shape_key]`` -- measured on this exact SKU.
    2. ``shapes["any"][shape_key]`` -- measured, but published without a SKU.
    3. ``fwd[feature_bucket]`` -- the hand-authored feature default.

    ``feature_bucket`` is decided by the caller because the two backends carry
    different feature semantics (fp8 for gluon, dropout and small-head for
    triton) and those belong with the kernel that understands them. What lives
    here is the part both share: where the file is and how the tiers stack.

    Returns a fresh dict, safe to mutate.
    """
    document = load_config_json_merged(mha_config_relpath(backend))
    fwd = document["fwd"]
    shapes = fwd.get("shapes") or {}

    config = None
    if shape_key is not None:
        for tier in (current_mha_hardware_key(), HARDWARE_ANY):
            entry = shapes.get(tier, {}).get(shape_key)
            if entry is not None:
                config = dict(entry)
                break
    if config is None:
        config = dict(fwd[feature_bucket])

    _record_resolved_config(backend, config)
    return config


def _record_resolved_config(backend: str, config: dict) -> None:
    """Report the resolved config to an in-flight selection proof, if any.

    This is the only place that knows which tiles a Triton or Gluon launch
    will actually use, so it is the only honest place to observe them from.
    Imported lazily to keep the config machinery free of an op-layer import.
    """
    try:
        from aiter.ops.mha_fwd_policy import record_mha_fwd_selection
    except ImportError:  # pragma: no cover - policy module is optional here
        return
    record_mha_fwd_selection(config=config, config_backend=backend)
