// SPDX-License-Identifier: MIT
// Copyright (C) 2024-2026, Advanced Micro Devices, Inc. All rights reserved.

#include "aiter_stream.h"
#include "iq2r.h"
#include "rocm_ops.hpp"

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m)
{
    AITER_SET_STREAM_PYBIND;
    m.def("iq2r_encode_out",
          &aiter::iq2r_encode_out,
          py::arg("weight"),
          py::arg("importance"),
          py::arg("codebook"),
          py::arg("indices"),
          py::arg("scales"),
          py::arg("data"),
          py::arg("auxiliary"),
          py::arg("scale_delta_overflow"),
          py::arg("valid_k"),
          py::arg("exponent_radius"),
          py::arg("codebook_max"));
    m.def("iq2r_materialize_out",
          &aiter::iq2r_materialize_out,
          py::arg("data"),
          py::arg("auxiliary"),
          py::arg("output"),
          py::arg("logical_n"),
          py::arg("logical_k"),
          py::arg("expert_index"));
    m.def("iq2r_gemm_out",
          &aiter::iq2r_gemm_out,
          py::arg("activations"),
          py::arg("activation_scales"),
          py::arg("data"),
          py::arg("auxiliary"),
          py::arg("bias"),
          py::arg("output"),
          py::arg("logical_n"),
          py::arg("logical_k"),
          py::arg("tile_n"),
          py::arg("expert_index"));
    m.def("iq2r_task_gemm_out",
          &aiter::iq2r_task_gemm_out,
          py::arg("activations"),
          py::arg("activation_scales"),
          py::arg("data"),
          py::arg("auxiliary"),
          py::arg("tasks"),
          py::arg("task_count"),
          py::arg("bias"),
          py::arg("output"),
          py::arg("logical_n"),
          py::arg("logical_k"),
          py::arg("tile_n"));
    m.def("iq2r_task_gemm_indexed_out",
          &aiter::iq2r_task_gemm_indexed_out,
          py::arg("activations"),
          py::arg("activation_scales"),
          py::arg("data"),
          py::arg("auxiliary"),
          py::arg("tasks"),
          py::arg("task_count"),
          py::arg("bias"),
          py::arg("output"),
          py::arg("logical_n"),
          py::arg("logical_k"),
          py::arg("tile_n"),
          py::arg("gather_indices"));
    m.def("iq2r_task_gemm_swiglu_quant_out",
          &aiter::iq2r_task_gemm_swiglu_quant_out,
          py::arg("activations"),
          py::arg("activation_scales"),
          py::arg("data"),
          py::arg("auxiliary"),
          py::arg("tasks"),
          py::arg("task_count"),
          py::arg("bias"),
          py::arg("output"),
          py::arg("output_scales"),
          py::arg("logical_n"),
          py::arg("logical_k"),
          py::arg("limit")     = 0.0,
          py::arg("alpha")     = 1.0,
          py::arg("up_offset") = 0.0);
    m.def("iq2r_route_sort_tasks_out",
          &aiter::iq2r_route_sort_tasks_out,
          py::arg("expert_ids"),
          py::arg("sorted_expert_ids"),
          py::arg("gather_indices"),
          py::arg("scatter_indices"),
          py::arg("tasks"),
          py::arg("task_count"),
          py::arg("expert_map"),
          py::arg("expert_count"),
          py::arg("expert_start"),
          py::arg("expert_stride"),
          py::arg("task_rows"),
          py::arg("drop_nonlocal_tasks") = false);
    m.def("iq2r_route_gather_indexed_out",
          &aiter::iq2r_route_gather_indexed_out,
          py::arg("input"),
          py::arg("gather_indices"),
          py::arg("output"),
          py::arg("topk"));
    m.def("iq2r_route_gather_quant_out",
          &aiter::iq2r_route_gather_quant_out,
          py::arg("input"),
          py::arg("gather_indices"),
          py::arg("output"),
          py::arg("scales"),
          py::arg("topk"));
    m.def("iq2r_route_scatter_quant_out",
          &aiter::iq2r_route_scatter_quant_out,
          py::arg("input"),
          py::arg("scatter_indices"),
          py::arg("output"),
          py::arg("scales"),
          py::arg("topk"));
    m.def("iq2r_route_direct_gather_quant_out",
          &aiter::iq2r_route_direct_gather_quant_out,
          py::arg("input"),
          py::arg("expert_ids"),
          py::arg("sorted_expert_ids"),
          py::arg("gather_indices"),
          py::arg("scatter_indices"),
          py::arg("tasks"),
          py::arg("task_count"),
          py::arg("output"),
          py::arg("scales"),
          py::arg("expert_map"),
          py::arg("topk"),
          py::arg("expert_count"),
          py::arg("expert_start"),
          py::arg("expert_stride"),
          py::arg("drop_nonlocal_routes") = false);
    m.def("iq2r_route_topk_direct_gather_quant_out",
          &aiter::iq2r_route_topk_direct_gather_quant_out,
          py::arg("input"),
          py::arg("router_logits"),
          py::arg("topk_weights"),
          py::arg("topk_ids"),
          py::arg("sorted_expert_ids"),
          py::arg("gather_indices"),
          py::arg("scatter_indices"),
          py::arg("tasks"),
          py::arg("task_count"),
          py::arg("output"),
          py::arg("scales"),
          py::arg("renormalize"),
          py::arg("router_bias")           = std::nullopt,
          py::arg("biased_sigmoid")        = false,
          py::arg("routed_scaling_factor") = 1.0,
          py::arg("expert_map")            = std::nullopt,
          py::arg("expert_count")          = 128,
          py::arg("expert_start")          = 0,
          py::arg("expert_stride")         = 1,
          py::arg("drop_nonlocal_routes")  = false);
    m.def("iq2r_route_topk_sort_gather_quant_out",
          &aiter::iq2r_route_topk_sort_gather_quant_out,
          py::arg("input"),
          py::arg("router_logits"),
          py::arg("topk_weights"),
          py::arg("topk_ids"),
          py::arg("sorted_expert_ids"),
          py::arg("gather_indices"),
          py::arg("scatter_indices"),
          py::arg("tasks"),
          py::arg("task_count"),
          py::arg("output"),
          py::arg("scales"),
          py::arg("task_rows"),
          py::arg("renormalize"),
          py::arg("router_bias")           = std::nullopt,
          py::arg("biased_sigmoid")        = false,
          py::arg("routed_scaling_factor") = 1.0,
          py::arg("expert_map")            = std::nullopt,
          py::arg("expert_count")          = 128,
          py::arg("expert_start")          = 0,
          py::arg("expert_stride")         = 1,
          py::arg("drop_nonlocal_routes")  = false);
    m.def("iq2r_swiglu_out",
          &aiter::iq2r_swiglu_out,
          py::arg("gate_up"),
          py::arg("output"),
          py::arg("limit"),
          py::arg("alpha"),
          py::arg("up_offset"));
    m.def("iq2r_swiglu_quant_out",
          &aiter::iq2r_swiglu_quant_out,
          py::arg("gate_up"),
          py::arg("output"),
          py::arg("scales"),
          py::arg("activated") = std::nullopt,
          py::arg("limit")     = 7.0,
          py::arg("alpha")     = 1.702,
          py::arg("up_offset") = 1.0);
    m.def("iq2r_swiglu_quant_scatter_out",
          &aiter::iq2r_swiglu_quant_scatter_out,
          py::arg("gate_up"),
          py::arg("scatter_indices"),
          py::arg("output"),
          py::arg("scales"),
          py::arg("topk"),
          py::arg("activated") = std::nullopt,
          py::arg("limit")     = 7.0,
          py::arg("alpha")     = 1.702,
          py::arg("up_offset") = 1.0);
    m.def("iq2r_route_reduce_indexed_out",
          &aiter::iq2r_route_reduce_indexed_out,
          py::arg("route_output"),
          py::arg("route_weights"),
          py::arg("scatter_indices"),
          py::arg("output"),
          py::arg("topk"));
    m.def("iq2r_route_reduce_add_indexed_out",
          &aiter::iq2r_route_reduce_add_indexed_out,
          py::arg("route_output"),
          py::arg("route_weights"),
          py::arg("scatter_indices"),
          py::arg("shared_output"),
          py::arg("output"),
          py::arg("topk"));
    m.def("iq2r_route_reduce_add_rmsnorm_indexed_out",
          &aiter::iq2r_route_reduce_add_rmsnorm_indexed_out,
          py::arg("route_output"),
          py::arg("route_weights"),
          py::arg("scatter_indices"),
          py::arg("residual"),
          py::arg("norm_weight"),
          py::arg("output"),
          py::arg("residual_out"),
          py::arg("topk"),
          py::arg("epsilon"),
          py::arg("block_size"));
    m.def("iq2r_gate_aligned_fused_out", &aiter::iq2r_gate_aligned_fused_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("gather"), py::arg("output"), py::arg("output_scales"), py::arg("rows_per_cta"));
    m.def("iq2r_gate_quad_fused_out", &aiter::iq2r_gate_quad_fused_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("gather"), py::arg("output"), py::arg("output_scales"), py::arg("rows_per_cta"));
    m.def("iq2r_gate_quad_sparse_out", &aiter::iq2r_gate_quad_sparse_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("gather"), py::arg("output"), py::arg("output_scales"), py::arg("rows_per_cta"));
    m.def("iq2r_gate_quad_splitk_out", &aiter::iq2r_gate_quad_splitk_out, py::arg("input"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("partials"), py::arg("output"), py::arg("output_scales"), py::arg("physical_waves"));
    m.def("iq2r_gate_quad_route_fused_out", &aiter::iq2r_gate_quad_route_fused_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("output"), py::arg("output_scales"));
    m.def("iq2r_down_sparse_large32_out", &aiter::iq2r_down_sparse_large32_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("output"), py::arg("grid_multiplier"));
    m.def("iq2r_down_sparse_scheduled_out", &aiter::iq2r_down_sparse_scheduled_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("output"), py::arg("grid_multiplier"), py::arg("variant"));
    m.def("iq2r_down_shortk_out", &aiter::iq2r_down_shortk_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("output"), py::arg("grid_multiplier"), py::arg("variant"));
    m.def("iq2r_gate_quad_scheduled_out", &aiter::iq2r_gate_quad_scheduled_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("output"), py::arg("output_scales"), py::arg("variant"));
    m.def("iq2r_down_token_fused48_out", &aiter::iq2r_down_token_fused48_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("expert_ids"), py::arg("scatter"), py::arg("route_weights"), py::arg("output"));
    m.def("iq2r_down_token_route9_out", &aiter::iq2r_down_token_route9_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("expert_ids"), py::arg("scatter"), py::arg("route_weights"), py::arg("output"));
    m.def("iq2r_glm53_tp4_gate_out", &aiter::iq2r_glm53_tp4_gate_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("output"), py::arg("output_scales"), py::arg("variant"));
    m.def("iq2r_glm53_tp4_down_out", &aiter::iq2r_glm53_tp4_down_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("output"), py::arg("grid_multiplier"), py::arg("variant"));
    m.def("iq2r_glm53_tp4_route9_out", &aiter::iq2r_glm53_tp4_route9_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("expert_ids"), py::arg("scatter"), py::arg("route_weights"), py::arg("output"));
    m.def("iq2r_glm53_tp4_indexed_gate_out", &aiter::iq2r_glm53_tp4_indexed_gate_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("gather"), py::arg("output"), py::arg("output_scales"), py::arg("rows_per_cta"));
    m.def("iq2r_glm53_tp4_large_down_out", &aiter::iq2r_glm53_tp4_large_down_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("output"), py::arg("grid_multiplier"), py::arg("variant"));
    m.def("iq2r_down_token_pair9_out", &aiter::iq2r_down_token_pair9_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("expert_ids"), py::arg("scatter"), py::arg("route_weights"), py::arg("output"), py::arg("group_tokens"));
    m.def("iq2r_glm53_dense_gate_out", &aiter::iq2r_glm53_dense_gate_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("tasks"), py::arg("task_count"), py::arg("gather"), py::arg("output"), py::arg("output_scales"), py::arg("rows_per_cta"), py::arg("variant"));
    m.def("iq2r_down_token_adaptive9_out", &aiter::iq2r_down_token_adaptive9_out, py::arg("activations"), py::arg("scales"), py::arg("data"), py::arg("auxiliary"), py::arg("expert_ids"), py::arg("scatter"), py::arg("route_weights"), py::arg("output"), py::arg("task_count"), py::arg("task_table"));
}
