// SPDX-License-Identifier: MIT
// Copyright (C) 2026, Advanced Micro Devices, Inc. All rights reserved.

#ifndef __HIP_DEVICE_COMPILE__

#include "aiter_stream.h"
#include "opus_moe_backward.h"
#include "rocm_ops.hpp"

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m)
{
    AITER_SET_STREAM_PYBIND
    m.def("opus_moe_router_bwd",
          &opus_moe_router_bwd,
          "Opus MoE selected-softmax router backward",
          py::arg("d_scores"),
          py::arg("scores"),
          py::arg("topk_ids"),
          py::arg("d_logits"),
          py::arg("kernel_id") = -1);
    m.def("opus_moe_db1_bwd",
          &opus_moe_db1_bwd,
          "Opus MoE expert up/gate bias backward",
          py::arg("d_z"),
          py::arg("sorted_token_ids"),
          py::arg("num_valid_ids"),
          py::arg("expert_padded_offsets"),
          py::arg("d_b1"),
          py::arg("token_num"),
          py::arg("topk"),
          py::arg("block_m"),
          py::arg("kernel_id") = -1);
    m.def("opus_moe_bias_down_bwd",
          &opus_moe_bias_down_bwd,
          "Opus MoE down bias dscore and db2 backward",
          py::arg("d_out"),
          py::arg("scores"),
          py::arg("b2"),
          py::arg("sorted_token_ids"),
          py::arg("sorted_expert_ids"),
          py::arg("num_valid_ids"),
          py::arg("expert_padded_offsets"),
          py::arg("d_scores"),
          py::arg("d_b2"),
          py::arg("block_m"),
          py::arg("kernel_id") = -1);
    m.def("opus_moe_varlen_down_bwd",
          &opus_moe_varlen_down_bwd,
          "Opus MoE compact variable-routing down backward",
          py::arg("d_out"),
          py::arg("z"),
          py::arg("w2"),
          py::arg("scores"),
          py::arg("b2"),
          py::arg("sorted_route_ids"),
          py::arg("sorted_expert_ids"),
          py::arg("num_valid_ids"),
          py::arg("route_to_token"),
          py::arg("expert_padded_offsets"),
          py::arg("d_scores_workspace"),
          py::arg("d_z"),
          py::arg("a_scaled"),
          py::arg("d_scores"),
          py::arg("d_w2"),
          py::arg("d_b2"),
          py::arg("block_m"),
          py::arg("has_bias"),
          py::arg("compute_dz"),
          py::arg("compute_dw2"),
          py::arg("compute_dscore"),
          py::arg("compute_db2"),
          py::arg("down_kernel_id") = -1,
          py::arg("dw2_kernel_id") = -1,
          py::arg("bias_kernel_id") = -1);
    m.def("opus_moe_varlen_up_bwd",
          &opus_moe_varlen_up_bwd,
          "Opus MoE compact variable-routing up backward",
          py::arg("d_z"),
          py::arg("x"),
          py::arg("w1"),
          py::arg("sorted_route_ids"),
          py::arg("sorted_expert_ids"),
          py::arg("num_valid_ids"),
          py::arg("route_to_token"),
          py::arg("token_route_offsets"),
          py::arg("expert_padded_offsets"),
          py::arg("d_x_route"),
          py::arg("d_x"),
          py::arg("d_w1"),
          py::arg("d_b1"),
          py::arg("block_m"),
          py::arg("compute_dx"),
          py::arg("compute_dw1"),
          py::arg("compute_db1"),
          py::arg("route_dx_kernel_id") = -1,
          py::arg("route_reduce_kernel_id") = -1,
          py::arg("dw1_kernel_id") = -1,
          py::arg("bias_kernel_id") = -1);
    m.def("opus_moe_varlen_router_bwd",
          &opus_moe_varlen_router_bwd,
          "Opus MoE compact selected-softmax router backward",
          py::arg("d_scores"),
          py::arg("scores"),
          py::arg("route_expert_ids"),
          py::arg("token_route_offsets"),
          py::arg("d_logits"),
          py::arg("kernel_id") = -1);
    m.def("opus_moe_down_bwd",
          &opus_moe_down_bwd,
          "Opus MoE fused down-projection backward",
          py::arg("d_out"),
          py::arg("z"),
          py::arg("w2"),
          py::arg("scores"),
          py::arg("sorted_token_ids"),
          py::arg("sorted_expert_ids"),
          py::arg("num_valid_ids"),
          py::arg("d_scores_workspace"),
          py::arg("d_z"),
          py::arg("a_scaled"),
          py::arg("d_scores"),
          py::arg("block_m"),
          py::arg("kernel_id") = -1);
    m.def("opus_moe_route_bwd",
          &opus_moe_route_bwd,
          "Opus MoE route input-gradient backward",
          py::arg("d_z"),
          py::arg("w1"),
          py::arg("sorted_token_ids"),
          py::arg("sorted_expert_ids"),
          py::arg("num_valid_ids"),
          py::arg("expert_padded_offsets"),
          py::arg("reverse_sorted"),
          py::arg("d_x_route"),
          py::arg("d_x"),
          py::arg("block_m"),
          py::arg("route_dx_kernel_id") = -1,
          py::arg("route_reduce_kernel_id") = -1);
    m.def("opus_moe_weight_bwd",
          &opus_moe_weight_bwd,
          "Opus MoE grouped weight-gradient backward",
          py::arg("x"),
          py::arg("d_out"),
          py::arg("d_z"),
          py::arg("a_scaled"),
          py::arg("sorted_token_ids"),
          py::arg("num_valid_ids"),
          py::arg("expert_padded_offsets"),
          py::arg("d_w1"),
          py::arg("d_w2"),
          py::arg("topk"),
          py::arg("block_m"),
          py::arg("dw1_kernel_id") = -1,
          py::arg("dw2_kernel_id") = -1);
    m.def("opus_moe_dw1_bwd",
          &opus_moe_dw1_bwd,
          "Opus MoE grouped dW1 backward",
          py::arg("x"),
          py::arg("d_z"),
          py::arg("sorted_token_ids"),
          py::arg("num_valid_ids"),
          py::arg("expert_padded_offsets"),
          py::arg("d_w1"),
          py::arg("topk"),
          py::arg("block_m"),
          py::arg("kernel_id") = -1);
    m.def("opus_moe_dw2_bwd",
          &opus_moe_dw2_bwd,
          "Opus MoE grouped dW2 backward",
          py::arg("d_out"),
          py::arg("a_scaled"),
          py::arg("sorted_token_ids"),
          py::arg("num_valid_ids"),
          py::arg("expert_padded_offsets"),
          py::arg("d_w2"),
          py::arg("topk"),
          py::arg("block_m"),
          py::arg("kernel_id") = -1);
    m.def("opus_moe_full_bwd",
          &opus_moe_full_bwd,
          "Opus MoE complete K1--K5 backward launch chain",
          py::arg("d_out"),
          py::arg("x"),
          py::arg("z"),
          py::arg("w1"),
          py::arg("w2"),
          py::arg("scores"),
          py::arg("sorted_token_ids"),
          py::arg("sorted_expert_ids"),
          py::arg("num_valid_ids"),
          py::arg("reverse_sorted"),
          py::arg("expert_padded_offsets"),
          py::arg("d_scores_workspace"),
          py::arg("d_z"),
          py::arg("a_scaled"),
          py::arg("d_scores"),
          py::arg("d_x_route"),
          py::arg("d_x"),
          py::arg("d_w1"),
          py::arg("d_w2"),
          py::arg("block_m"),
          py::arg("down_kernel_id") = -1,
          py::arg("route_dx_kernel_id") = -1,
          py::arg("route_reduce_kernel_id") = -1,
          py::arg("dw1_kernel_id") = -1,
          py::arg("dw2_kernel_id") = -1);
    m.def("opus_moe_full_bwd_trusted",
          &opus_moe_full_bwd_trusted,
          "Trusted Opus MoE complete K1--K5 backward launch chain",
          py::arg("d_out"),
          py::arg("x"),
          py::arg("z"),
          py::arg("w1"),
          py::arg("w2"),
          py::arg("scores"),
          py::arg("sorted_token_ids"),
          py::arg("sorted_expert_ids"),
          py::arg("num_valid_ids"),
          py::arg("reverse_sorted"),
          py::arg("expert_padded_offsets"),
          py::arg("d_scores_workspace"),
          py::arg("d_z"),
          py::arg("a_scaled"),
          py::arg("d_scores"),
          py::arg("d_x_route"),
          py::arg("d_x"),
          py::arg("d_w1"),
          py::arg("d_w2"),
          py::arg("block_m"),
          py::arg("down_kernel_id") = -1,
          py::arg("route_dx_kernel_id") = -1,
          py::arg("route_reduce_kernel_id") = -1,
          py::arg("dw1_kernel_id") = -1,
          py::arg("dw2_kernel_id") = -1);
}

#endif // !__HIP_DEVICE_COMPILE__
