// SPDX-License-Identifier: MIT
// Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
//
// Cross-arch traits umbrella: aggregates the per-arch traits headers so the
// dispatcher TU (opus_gemm.cu) and any per-arch glue header
// (opus_gemm_arch_<arch>.cuh) get all kargs / traits types in one include.
//
// Each arch's traits are guarded by OPUS_TARGET_<ARCH> (generated by
// gen_instances.py into opus_gemm_arch_config.h) so only the active
// arch's headers are included in a given build.
#pragma once

#include "opus_gemm_arch_config.h"

#if defined(OPUS_TARGET_GFX950)
#include "gfx950/opus_gemm_traits_a8w8_scale_gfx950.cuh"
#include "gfx950/opus_gemm_traits_a8w8_noscale_gfx950.cuh"
#include "gfx950/opus_gemm_traits_a16w16_gfx950.cuh"
#elif defined(OPUS_TARGET_GFX942)
#include "gfx942/opus_gemm_traits_a16w16.cuh"
#endif
