name: Aiter Release Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: false
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_DOCKER_IMAGE: "rocm/pytorch:latest"

jobs:
  build_whl_package:
    runs-on: aiter-k8s-build
  
    steps:
      - name: Checkout aiter repo
        uses: actions/checkout@v4
      
      - name: Sync submodules
        run: |
          set -e
          git submodule sync
          git submodule update --init --recursive --depth 1 --jobs 4
        
      - name: Run the container
        run: |
          set -ex
          echo "Starting container: aiter_build"
          docker run -dt \
          --shm-size=16G \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          --name aiter_build \
          ${{ env.BUILD_DOCKER_IMAGE }}

      - name: Install Dependencies
        run: |
          set -e
          echo "Install Dependencies"
          docker exec \
          -w /workspace \
          aiter_build \
          pip install -r requirements.txt 
          
      - name: Build Relase Package
        run: |
          set -e
          echo "Building aiter whl packages..."
          docker exec \
          -w /workspace \
          aiter_build \
          PREBUILD_KERNELS=1 GPU_ARCHS="gfx942;gfx950" python3 setup.py bdist_wheel && ls dist/*.whl
          
