name: Network Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  # Triggers on PRs targeting `main`
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  network-test:
    runs-on: aiter-1gpu-runner

    steps:
      - name: Install speedtest-cli and test network
        run: |
          set -ex
          pip install --user speedtest-cli && export PATH=$PATH:~/.local/bin && python3 -m speedtest_cli --simple
