name: Network Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  # Triggers on PRs targeting `main`
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  network-test:
    runs-on: aiter-1gpu-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
    
      - name: Install speedtest-cli and test network
        run: |
          set -ex
          pip install speedtest-cli && python -m speedtest_cli --simple