name: Network Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  # Triggers on PRs targeting `main`
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  network-test:
    strategy:
      fail-fast: false
      matrix:
        runner: [aiter-1gpu-runner, aiter-mi325-1gpu]

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Docker pull image
        run: |
          set -ex
          docker rmi rocm/pytorch:latest
          time docker pull rocm/pytorch:latest

      - name: Run the container
        run: |
          set -ex
          echo "Starting container: network_test"
          docker run -dt \
          --device=/dev/dri \
          --device=/dev/kfd \
          --shm-size=16G \
          --group-add $(getent group render | cut -d: -f3) \
          --group-add $(getent group video | cut -d: -f3) \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          --name network_test \
          rocm/pytorch:latest
    
      - name: Install speedtest-cli and test network
        run: |
          set -ex
          echo "Installing speedtest-cli and testing network..."
          docker exec \
          -w /workspace \
          network_test \
          bash -c "pip install speedtest-cli && speedtest-cli --simple"
