name: Operators Tunning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  # Triggers on PRs targeting `main`
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  operators_tunning:
    strategy:
      fail-fast: false
      matrix:
        runner: [aiter-mi355-1gpu] # TODO: add more runners
    name: Operators Tunning
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout aiter repo
        uses: actions/checkout@v4

      - name: Sync submodules
        run: |
          set -e
          git submodule sync
          git submodule update --init --recursive --depth 1 --jobs 4

      - name: Clean up Rocm processes
        run: |
          ./.github/scripts/clean_up_rocm.sh

      - name: Run the container
        run: |
          set -ex
          echo "Starting container: operators_tunning_test"
          docker run -dt \
          --device=/dev/dri \
          --device=/dev/kfd \
          --shm-size=16G \
          --group-add $(getent group render | cut -d: -f3) \
          --group-add $(getent group video | cut -d: -f3) \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          --name operators_tunning_test \
          rocm/pytorch:latest

      - name: Setup-Triton
        run: |
          set -ex
          echo "Setuping Triton..."
          docker exec \
          -w /workspace \
          operators_tunning_test \
          ./.github/scripts/build_triton.sh

      - name: Show Computing Units
        run: |
          set -ex
          echo "Showing Computing Units..."
          docker exec \
          -w /workspace \
          operators_tunning_test \
          rocminfo | grep -i 'Compute Unit'
    
      - name: Test Performance before tunning
        run: |
          set -ex
          docker exec \
          -w /workspace \
          operators_tunning_test \
          ./.github/scripts/op_tune.sh test
    
      - name: Operators Tunning Tests
        run: |
          set -ex
          echo "Running Operators Tunning Tests..."
          docker exec \
          -w /workspace \
          operators_tunning_test \
          ./.github/scripts/op_tune.sh tune
      
      - name: Show the difference after tunning
        run: |
          set -ex
          git diff --word-diff

      - name: Test Performance after tunning
        run: |
          set -ex
          docker exec \
          -w /workspace \
          operators_tunning_test \
          ./.github/scripts/op_tune.sh test