name: sglang workflow

on:
  pull_request:
    branches: [main]  # Triggers on PRs targeting `main`

jobs:
  sglang:
    name: sglnag integration
    runs-on: [mi300x-8gpu]
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - name: Checkout aiter repo
        uses: actions/checkout@v4

      - name: Clone sglang repo
        run: |
          git clone https://github.com/sgl-project/sglang.git
      - name: Build  Image
        run: |
          cd sglang
          docker build --no-cache -f docker/Dockerfile \
            --build-arg AITER_BRANCH=main \
            --build-arg PYTORCH_ROCM_ARCH=gfx942 \
            -t sglang_aiter_base .
            
      - name: Start CI container
        run: bash sglang/scripts/amd_ci_start_container.sh
        #env:
        #  GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Install dependencies
        run: bash sglang/scripts/amd_ci_install_dependency.sh

      - name: Evaluate Accuracy
        timeout-minutes: 30
        run: |
          bash sglang/scripts/amd_ci_exec.sh -e SGLANG_USE_AITER=0 python3 test_eval_accuracy_large.py
          bash sglang/scripts/amd_ci_exec.sh python3 test_eval_fp8_accuracy.py
          bash sglang/scripts/amd_ci_exec.sh python3 models/test_qwen_models.py



